# Generated by Django 4.0.3 on 2022-10-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
