# Generated by Django 4.0.3 on 2022-10-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('time_create',), 'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
