# Generated by Django 4.0.3 on 2022-10-30 22:25

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', validators=[home.models.validate_image], verbose_name='Картинка'),
        ),
    ]
